### PR TITLE
Ethers.js 101, Ethers.js 102, and Solidity 104 English Translations

### PR DESCRIPTION
**Pull request by 22Xy**
As discussed in issue https://github.com/WTFAcademy/frontend/issues/118, 
- Translate Solidity 104 Security Course into English under `i18n\en\docusaurus-plugin-content-docs-solidity-104`
- Add Ethers.js 101 & Ethers.js 102 translations from [WTF Ethers](https://github.com/WTFAcademy/WTF-Ethers/tree/main/en) to frontend i18n.

### CODE REVIEW

**Comment by 22Xy** [comment]
@AmazingAng @chongqiangchen looking for your review :)

**Comment by 22Xy** [comment]
@chongqiangchen Hi, could you review this PR? Thank you!

**Comment by chongqiangchen** [comment]
> @chongqiangchen Hi, could you review this PR? Thank you!

this needs to be reviewed by @AmazingAng

**Comment by AmazingAng** [comment]
Sure, i will review asap

**Comment by AmazingAng** [comment]
Merged thx @22Xy !

**Pull request merged**
